In [ ]:
import pandas as pd

df = pd.read_excel('/content/pos_tagged.xlsx')
display(df.head())

                                               Value
0              1\QT_QTC .\RD_PUNC 0\QT_QTC .\RD_PUNC
1  थेवबो\CC_CCS 1658\N_NN मायथायाव\N_NN जन\N_NNP ...
2  मुलुगनि\N_NN गुबुन\JJ गुबुन\V_VAUX थुनलाइनि\N_...
3  खुगाजों\N_NN खुगा\N_NN सोलिबोनाय\V_VM गथ’\N_NN...
4  मिसनारिफोरा\N_NN रनसायनाय\V_VM आरो\CC_CCD रावस...

In [ ]:
def parse_pos_tagged_string(text):
    words = []
    pos_tags = []
    if pd.isna(text):
        return [], []
    # Split the string by spaces to get individual word\tag units
    word_tag_units = text.strip().split(' ')
    for unit in word_tag_units:
        if unit:
            # Split each unit by the last backslash to separate word and tag
            parts = unit.rsplit('\\', 1)
            if len(parts) == 2:
                words.append(parts[0])
                pos_tags.append(parts[1])
            else:
                # If no backslash is found, treat the whole unit as a word and tag as None/empty
                words.append(unit)
                pos_tags.append(None) # Or consider 'UNKNOWN_TAG' based on expected data quality
    return words, pos_tags

# Apply the function to the 'Value' column to create new 'Words' and 'POS_Tags' columns
df['Words'], df['POS_Tags'] = zip(*df['Value'].apply(parse_pos_tagged_string))

# Display the DataFrame with the new columns
display(df.head())

,Value,Words,POS_Tags
0,1\QT_QTC .\RD_PUNC 0\QT_QTC .\RD_PUNC,"[1, ., 0, .]","[QT_QTC, RD_PUNC, QT_QTC, RD_PUNC]"
1,थेवबो\CC_CCS 1658\N_NN मायथायाव\N_NN जन\N_NNP ...,"[थेवबो, 1658, मायथायाव, जन, असम, कमेनस्कि, (, ...","[CC_CCS, N_NN, N_NN, N_NNP, N_NNP, N_NNP, RD_P..."
2,मुलुगनि\N_NN गुबुन\JJ गुबुन\V_VAUX थुनलाइनि\N_...,"[मुलुगनि, गुबुन, गुबुन, थुनलाइनि, बादिनो, बर’,...","[N_NN, JJ, V_VAUX, N_NNP, PSP, N_NNP, N_NNP, N..."
3,खुगाजों\N_NN खुगा\N_NN सोलिबोनाय\V_VM गथ’\N_NN...,"[खुगाजों, खुगा, सोलिबोनाय, गथ’, थुनलाया, सिगां...","[N_NN, N_NN, V_VM, N_NNP, N_NNP, N_NST, V_VM, ..."
4,मिसनारिफोरा\N_NN रनसायनाय\V_VM आरो\CC_CCD रावस...,"[मिसनारिफोरा, रनसायनाय, आरो, रावसोलायनाय, बाइब...","[N_NN, V_VM, CC_CCD, V_VM, N_NNP, N_NN, RD_PUN..."

In [ ]:
print(type(df["Words"][0]))
print(type(df["POS_Tags"][0]))

<class 'list'>
<class 'list'>

In [ ]:
sentences = df["Words"].tolist()
labels = df["POS_Tags"].tolist()

print("Total sentences:", len(sentences))
print(sentences[0])
print(labels[0])

Total sentences: 6005
['1', '.', '0', '.']
['QT_QTC', 'RD_PUNC', 'QT_QTC', 'RD_PUNC']

In [ ]:
for i in range(len(sentences)):
    assert len(sentences[i]) == len(labels[i])

print("✅ Every sentence has matching labels.")

✅ Every sentence has matching labels.

In [ ]:
unique_tags = sorted(set(tag for sentence in labels for tag in sentence))

print("Number of POS tags:", len(unique_tags))
print(unique_tags)

Number of POS tags: 35
['CC_CCD', 'CC_CCS', 'DM_DMD', 'DM_DMI', 'DM_DMQ', 'DM_DMR', 'JJ', 'N_NN', 'N_NNP', 'N_NST', 'PR_PRC', 'PR_PRF', 'PR_PRI', 'PR_PRL', 'PR_PRP', 'PR_PRQ', 'PSP', 'QT_QTC', 'QT_QTF', 'QT_QTO', 'RB', 'RD_ECH', 'RD_PUNC', 'RD_RDF', 'RD_SYM', 'RD_UNK', 'RP_INJ', 'RP_INTF', 'RP_NEG', 'RP_RPD', 'V_VAUX', 'V_VAUX_VF', 'V_VM', 'V_VM_VF', 'V_VM_VNF']

In [ ]:
label2id = {label: idx for idx, label in enumerate(unique_tags)}
id2label = {idx: label for label, idx in label2id.items()}

print(label2id)

{'CC_CCD': 0, 'CC_CCS': 1, 'DM_DMD': 2, 'DM_DMI': 3, 'DM_DMQ': 4, 'DM_DMR': 5, 'JJ': 6, 'N_NN': 7, 'N_NNP': 8, 'N_NST': 9, 'PR_PRC': 10, 'PR_PRF': 11, 'PR_PRI': 12, 'PR_PRL': 13, 'PR_PRP': 14, 'PR_PRQ': 15, 'PSP': 16, 'QT_QTC': 17, 'QT_QTF': 18, 'QT_QTO': 19, 'RB': 20, 'RD_ECH': 21, 'RD_PUNC': 22, 'RD_RDF': 23, 'RD_SYM': 24, 'RD_UNK': 25, 'RP_INJ': 26, 'RP_INTF': 27, 'RP_NEG': 28, 'RP_RPD': 29, 'V_VAUX': 30, 'V_VAUX_VF': 31, 'V_VM': 32, 'V_VM_VF': 33, 'V_VM_VNF': 34}

In [ ]:
from sklearn.model_selection import train_test_split

train_sentences, temp_sentences, train_labels, temp_labels = train_test_split(
    sentences,
    labels,
    test_size=0.2,
    random_state=42
)

val_sentences, test_sentences, val_labels, test_labels = train_test_split(
    temp_sentences,
    temp_labels,
    test_size=0.5,
    random_state=42
)

print("Training:", len(train_sentences))
print("Validation:", len(val_sentences))
print("Testing:", len(test_sentences))

Training: 4804
Validation: 600
Testing: 601

In [ ]:
!pip install transformers datasets evaluate seqeval accelerate -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.9 MB/s eta 0:00:00
  Building wheel for seqeval (setup.py) ... done

In [ ]:
import numpy as np
import torch

from datasets import Dataset, DatasetDict

from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer
)

import evaluate

In [ ]:
MODEL_NAME = "alayaran/bodo-bert-mlm-base-article"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

config.json:   0%|          | 0.00/917 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/519 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/894k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.69M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

In [ ]:
sample = train_sentences[0]

encoding = tokenizer(
    sample,
    is_split_into_words=True
)

print(sample)
print(tokenizer.convert_ids_to_tokens(encoding["input_ids"]))

['बे', 'बाथ्राखौ', 'मोनसे', 'गोजौ', 'थाखोनि', 'बिजिरनाय', 'एबा', 'स्टादिनिफ्राय', 'मिथिनो', 'मोननाय', 'जादों', '।']
['[CLS]', 'ब', 'बाथराखौ', 'मोनस', 'गोजौ', 'थाखोनि', 'बिजिरनाय', 'एबा', 'सटा', '##दिनिफराय', 'मिथिनो', 'मोननाय', 'जादो', '।', '[SEP]']

In [ ]:
def tokenize_and_align_labels(sentences, labels):

    tokenized_inputs = tokenizer(
        sentences,
        truncation=True,
        padding=False,
        is_split_into_words=True
    )

    aligned_labels = []

    for i, label in enumerate(labels):

        word_ids = tokenized_inputs.word_ids(batch_index=i)

        previous_word_idx = None

        label_ids = []

        for word_idx in word_ids:

            if word_idx is None:
                label_ids.append(-100)

            elif word_idx != previous_word_idx:
                label_ids.append(label2id[label[word_idx]])

            else:
                label_ids.append(-100)

            previous_word_idx = word_idx

        aligned_labels.append(label_ids)

    tokenized_inputs["labels"] = aligned_labels

    return tokenized_inputs

In [ ]:
train_dataset = Dataset.from_dict({
    "tokens": train_sentences,
    "labels": train_labels
})

val_dataset = Dataset.from_dict({
    "tokens": val_sentences,
    "labels": val_labels
})

test_dataset = Dataset.from_dict({
    "tokens": test_sentences,
    "labels": test_labels
})

In [ ]:
train_dataset = train_dataset.map(
    lambda x: tokenize_and_align_labels(
        x["tokens"],
        x["labels"]
    ),
    batched=True
)

val_dataset = val_dataset.map(
    lambda x: tokenize_and_align_labels(
        x["tokens"],
        x["labels"]
    ),
    batched=True
)

test_dataset = test_dataset.map(
    lambda x: tokenize_and_align_labels(
        x["tokens"],
        x["labels"]
    ),
    batched=True
)

Map:   0%|          | 0/4804 [00:00<?, ? examples/s]

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

Map:   0%|          | 0/601 [00:00<?, ? examples/s]

In [ ]:
train_dataset = train_dataset.remove_columns(["tokens"])
val_dataset = val_dataset.remove_columns(["tokens"])
test_dataset = test_dataset.remove_columns(["tokens"])

In [ ]:
data_collator = DataCollatorForTokenClassification(tokenizer)

In [ ]:
model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  498MB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B /  498MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: alayaran/bodo-bert-mlm-base-article
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
print(train_dataset)
print(train_dataset[0])

Dataset({
    features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 4804
})
{'labels': [-100, 2, 9, 17, 6, 9, 32, 0, 25, -100, 32, 32, 32, 22, -100], 'input_ids': [2, 121, 1259, 599, 943, 1580, 5301, 640, 26073, 32065, 1158, 773, 675, 139, 3], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
from transformers import AutoModelForTokenClassification

MODEL_NAME = "alayaran/bodo-bert-mlm-base-article"

model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: alayaran/bodo-bert-mlm-base-article
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer)

In [ ]:
!pip install seqeval -q

In [ ]:
import numpy as np
import evaluate

seqeval = evaluate.load("seqeval")

Downloading builder script: 0.00B [00:00, ?B/s]

In [ ]:
def compute_metrics(eval_pred):

    predictions, labels = eval_pred

    predictions = np.argmax(predictions, axis=2)

    true_predictions = [
        [id2label[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    true_labels = [
        [id2label[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = seqeval.compute(
        predictions=true_predictions,
        references=true_labels
    )

    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(

    output_dir="./bodo_pos_model",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=5e-5, # Increased learning rate for hyperparameter tuning

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=10,

    weight_decay=0.01,

    logging_steps=50,

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    save_total_limit=2,

    report_to="none",

    # Updated from warmup_ratio to warmup_steps as recommended by the warning.
    # Calculated as 10% of total steps: 0.1 * (num_train_epochs * len(train_dataset) / per_device_train_batch_size)
    # 0.1 * (10 * 4804 / 8) = 0.1 * (10 * 600.5) = 600.5, rounded to 601.
    warmup_steps=601
)

In [ ]:
from collections import Counter
import torch

# Flatten the list of lists of true labels to count occurrences
all_train_labels = [label for sublist in train_labels for label in sublist]

# Count the occurrences of each label
label_counts = Counter(all_train_labels)

# Calculate inverse class weights
# The idea is to give less frequent classes higher weights
total_labels = sum(label_counts.values())
max_count = max(label_counts.values())

class_weights = torch.zeros(len(label2id))

for label_name, count in label_counts.items():
    if label_name in label2id:
        idx = label2id[label_name]
        # Inverse frequency weighting or inverse square root frequency
        # A common approach: 1 / frequency or N / (N_k * K) where N is total samples, N_k is samples for class k, K is number of classes
        # Here, I'll use a simpler inverse frequency scaled by total_labels/max_count to keep values manageable
        class_weights[idx] = total_labels / (count * len(label2id))

# Normalize weights so their sum is 1, or scale them as needed. Sometimes just raw inverse is used.
# For now, let's ensure minimum weight is not zero if a class isn't present (though all unique tags should be)
# and potentially normalize them.

# If a label doesn't appear in the training data, its count will be 0, leading to division by zero.
# We should handle cases where a label might not appear in all_train_labels if unique_tags contains more tags than present in train_labels.
# Based on previous checks, all unique_tags should be in train_labels, but it's good practice.
# Set weight to a small value for classes not appearing in train_labels to avoid inf, or to 0 depending on desired behavior.
for idx, label_name in id2label.items():
    if label_counts[label_name] == 0:
        class_weights[idx] = 0.0 # Or a very small number like 0.01

print("Class Weights:")
for idx, weight in enumerate(class_weights):
    print(f"  {id2label[idx]}: {weight:.4f}")

Class Weights:
  CC_CCD: 1.0510
  CC_CCS: 5.4792
  DM_DMD: 1.1134
  DM_DMI: 15.7734
  DM_DMQ: 24.2103
  DM_DMR: 160.1604
  JJ: 0.4913
  N_NN: 0.1109
  N_NNP: 0.2665
  N_NST: 0.7632
  PR_PRC: 40.8252
  PR_PRF: 9.9147
  PR_PRI: 6.2338
  PR_PRL: 35.2896
  PR_PRP: 2.0925
  PR_PRQ: 24.4951
  PSP: 1.3153
  QT_QTC: 1.0201
  QT_QTF: 4.4019
  QT_QTO: 4.5660
  RB: 1.4489
  RD_ECH: 6.9172
  RD_PUNC: 0.1951
  RD_RDF: 1.6724
  RD_SYM: 6.2525
  RD_UNK: 6.0350
  RP_INJ: 347.0143
  RP_INTF: 26.0261
  RP_NEG: 25.3913
  RP_RPD: 26.3555
  V_VAUX: 15.6548
  V_VAUX_VF: 1041.0428
  V_VM: 0.1503
  V_VM_VF: 1041.0428
  V_VM_VNF: 260.2607

In [ ]:
from torch.nn import CrossEntropyLoss

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None, **kwargs):
        labels = inputs.pop("labels")
        # forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")
        # compute custom loss
        loss_fct = CrossEntropyLoss(weight=class_weights.to(model.device))
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

In [ ]:
# Re-initialize the model to ensure it's in a fresh state before re-training with new parameters
model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

# Instantiate the custom trainer
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# Train the model with the updated learning rate and weighted loss
trainer.train()

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: alayaran/bodo-bert-mlm-base-article
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.decoder.bias               | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: V_VM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: N_NST seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: N_NN seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: JJ seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: CC_CCD seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RB seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RD_PUNC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PR_PRF seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: QT_QTF seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RD_SYM seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: N_NNP seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PSP seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PR_PRI seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: DM_DMD seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: CC_CCS seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RP_RPD seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: QT_QTC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: QT_QTO seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RD_RDF seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PR_PRP seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RD_ECH seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: V_VAUX seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RP_NEG seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: DM_DMI seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PR_PRQ seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: DM_DMQ seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RD_UNK seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PR_PRL seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: RP_INTF seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/sequence_labeling.py:171: UserWarning: PR_PRC seems not to be NE tag.
  warnings.warn('{} seems not to be NE tag.'.format(chunk))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [ ]:
test_results = trainer.evaluate(test_dataset)

print(f"New Test Accuracy: {test_results['eval_accuracy']:.4f}")
print(f"New Test F1 Score: {test_results['eval_f1']:.4f}")

In [ ]:
from transformers import Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

In [ ]:
trainer.train()

In [ ]:

import transformers
print(transformers.__version__)

In [ ]:
import transformers

print(transformers.__version__)
print(transformers.__file__)

In [ ]:
test_results = trainer.evaluate(test_dataset)

print(test_results)

In [ ]:
predictions, labels, metrics = trainer.predict(test_dataset)

In [ ]:
print(predictions.shape)

In [ ]:
predictions = np.argmax(predictions, axis=-1)

In [ ]:
pred_output = trainer.predict(test_dataset)

In [ ]:
import numpy as np

predictions = pred_output.predictions
labels = pred_output.label_ids

In [ ]:
print(predictions.shape)

In [ ]:
predicted_ids = np.argmax(predictions, axis=-1)

print(predicted_ids.shape)

In [ ]:
true_predictions = []
true_labels = []

for prediction, label in zip(predicted_ids, labels):

    pred_tags = []
    true_tags = []

    for p, l in zip(prediction, label):

        if l != -100:
            pred_tags.append(id2label[int(p)])
            true_tags.append(id2label[int(l)])

    true_predictions.append(pred_tags)
    true_labels.append(true_tags)

In [ ]:
true_predictions = [
    [id2label[int(p)] for p, l in zip(prediction, label) if l != -100]
    for prediction, label in zip(predicted_ids, labels)
]

true_labels = [
    [id2label[int(l)] for p, l in zip(prediction, label) if l != -100]
    for prediction, label in zip(predicted_ids, labels)
]

In [ ]:
from seqeval.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(true_labels, true_predictions))
print("Precision:", precision_score(true_labels, true_predictions))
print("Recall   :", recall_score(true_labels, true_predictions))
print("F1 Score :", f1_score(true_labels, true_predictions))

In [ ]:
from seqeval.metrics import classification_report

In [ ]:
from seqeval.metrics import classification_report
import pandas as pd

# The original line with the error:
# print(classification_report(true_labels, true_predictions))from seqeval.metrics import classification_report

# Corrected usage for printing the report directly (optional, as a DataFrame is printed later)
# print(classification_report(true_labels, true_predictions))

report = classification_report(
    true_labels,
    true_predictions,
    output_dict=True
)

report_df = pd.DataFrame(report).transpose()

print(report_df)

In [ ]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

true_flat = []
pred_flat = []

for t, p in zip(true_labels, true_predictions):
    true_flat.extend(t)
    pred_flat.extend(p)

cm = confusion_matrix(
    true_flat,
    pred_flat,
    labels=list(label2id.keys())
)

In [ ]:
plt.figure(figsize=(12, 12))

plt.imshow(cm)

plt.xticks(
    range(len(label2id)),
    label2id.keys(),
    rotation=90
)

plt.yticks(
    range(len(label2id)),
    label2id.keys()
)

plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")

plt.colorbar()

plt.tight_layout()

plt.show()

In [ ]:
print(f"Test Accuracy: {test_results['eval_accuracy']:.4f}")
print(f"Test F1 Score: {test_results['eval_f1']:.4f}")